name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Run tests
      run: pytest
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to test environment
      run: |
        kubectl apply -f k8s/test
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: yourusername/reponame:latest
    - name: Push to GitHub Packages
      uses: docker/push-action@v2
      with:
        tags: yourusername/reponame:latest
        registry: https://npm.pkg.github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
